# Generated by Django 5.1.2 on 2024-10-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumina', '0002_alter_datas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Mail',
            field=models.CharField(max_length=100),
        ),
    ]
